jobs:
  - name: spaceBar1
    type: runSh
    steps:
      - IN: runImageIN
      - OUT: runImageOUT
      - TASK:
        - script: sudo apt-get install tree
        - pwd

  # - name: spaceBar2
  #   type: runSh
  #   steps:
  #     - IN: sample-script-dup
  #     - IN: runImage
  #     - TASK:
  #       - script: sudo apt-get install tree
  #       - pwd
  #       - script: tree -F IN
  #       - script: IN/sample-script-dup/gitRepo/echo.sh
        
